[versions]
assertK = "0.25"
jetbrainsKotlinJvm = "2.2.20"
junit = "4.13.2"
koin = "4.0.0"
kord = "0.17.0"
kotlin = "2.2.20"
kotlin-date-time = "0.7.1"
kotlin-reflect = "1.9.22"
kotlinStdlib = "2.2.20"
kotlinx-coroutines = "1.10.2"
kotlinx-coroutines-test = "1.9.0"
kotlinx-serialization = "1.7.3"
ktor = "3.1.2"
napier = "2.7.1"
slf = "2.0.9"
sqldelight = "2.0.2"
turbine = "0.7.0"

[libraries]
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin-reflect" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-date-time = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-date-time" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# Ktor
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-slf = { module = "org.slf4j:slf4j-simple", version.ref = "slf" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# SQLDelight
sqldelight-driver-sqlite = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }

# Misc
kord = { module = "dev.kord:kord-core", version.ref = "kord" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
test-assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertK" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[bundles]
ktor = [
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-serialization-kotlinx-json",
    "ktor-logging",
]