package io.github.sophon.deadlock.remote.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
internal data class ItemDto(
    @SerialName("Name") val name: String? = null,
    @SerialName("Description") val description: String? = null,
    @SerialName("Cost") val cost: Int? = null,
    @SerialName("Tier") val tier: Int? = null,
    @SerialName("Activation") val activation: String? = null,
    @SerialName("Slot") val slot: String? = null,
    @SerialName("Components") val components: List<String>? = null,
    @SerialName("TargetTypes") val targetTypes: List<String>? = null,
    @SerialName("ShopFilters") val shopFilters: List<String>? = null,
    @SerialName("IsDisabled") val isDisabled: Boolean? = null,
    @SerialName("StreetBrawl") val streetBrawl: Boolean? = null,

    @SerialName("AbilityCooldown") val abilityCooldown: JsonElement? = null,
    @SerialName("AbilityCooldownBetweenCharge") val abilityCooldownBetweenCharge: JsonElement? = null,
    @SerialName("AbilityCastDelay") val abilityCastDelay: JsonElement? = null,
    @SerialName("AbilityCastRange") val abilityCastRange: JsonElement? = null,
    @SerialName("AbilityChannelTime") val abilityChannelTime: JsonElement? = null,
    @SerialName("AbilityDuration") val abilityDuration: JsonElement? = null,
    @SerialName("AbilityPostCastDuration") val abilityPostCastDuration: JsonElement? = null,
    @SerialName("AbilityUnitTargetLimit") val abilityUnitTargetLimit: JsonElement? = null,
    @SerialName("AbilityCharges") val abilityCharges: JsonElement? = null,

    @SerialName("ChannelMoveSpeed") val channelMoveSpeed: JsonElement? = null,

    @SerialName("Damage") val damage: JsonElement? = null,
    @SerialName("DPS") val dps: JsonElement? = null,
    @SerialName("NormalDPS") val normalDps: JsonElement? = null,
    @SerialName("MaxDPS") val maxDps: JsonElement? = null,
    @SerialName("DamageHeavyMelee") val damageHeavyMelee: JsonElement? = null,
    @SerialName("SpiritDamage") val spiritDamage: JsonElement? = null,
    @SerialName("ImpactDamage") val impactDamage: JsonElement? = null,
    @SerialName("HeadShotBonusDamage") val headShotBonusDamage: JsonElement? = null,
    @SerialName("DotHealthPercent") val dotHealthPercent: JsonElement? = null,
    @SerialName("DamagePulseAmount") val damagePulseAmount: JsonElement? = null,
    @SerialName("DPSIncrease") val dpsIncrease: JsonElement? = null,
    @SerialName("DPSMax") val dpsMax: JsonElement? = null,
    @SerialName("DamagePerChain") val damagePerChain: JsonElement? = null,
    @SerialName("ProcBaseAttackDamagePercent") val procBaseAttackDamagePercent: JsonElement? = null,
    @SerialName("ProcBaseAttackDamagePercentAltFire") val procBaseAttackDamagePercentAltFire: JsonElement? = null,

    @SerialName("TotalHealthRegen") val totalHealthRegen: JsonElement? = null,
    @SerialName("HealPerStack") val healPerStack: JsonElement? = null,
    @SerialName("LifestrikeHeal") val lifestrikeHeal: JsonElement? = null,
    @SerialName("LifestealHeal") val lifestealHeal: JsonElement? = null,
    @SerialName("LifestealHealPercent") val lifestealHealPercent: JsonElement? = null,
    @SerialName("HealPercentPerHeadshot") val healPercentPerHeadshot: JsonElement? = null,
    @SerialName("HealingPerCast") val healingPerCast: JsonElement? = null,
    @SerialName("Regeneration") val regeneration: JsonElement? = null,
    @SerialName("HealOnVeil") val healOnVeil: JsonElement? = null,

    @SerialName("VexBarrierCombatBarrier") val vexBarrierCombatBarrier: JsonElement? = null,
    @SerialName("CombatBarrier") val combatBarrier: JsonElement? = null,
    @SerialName("BonusPerChain") val bonusPerChain: JsonElement? = null,
    @SerialName("BonusHealth") val bonusHealth: JsonElement? = null,

    @SerialName("Radius") val radius: JsonElement? = null,
    @SerialName("TickRate") val tickRate: JsonElement? = null,
    @SerialName("SlowPercent") val slowPercent: JsonElement? = null,
    @SerialName("SlowDuration") val slowDuration: JsonElement? = null,
    @SerialName("StunDuration") val stunDuration: JsonElement? = null,
    @SerialName("DebuffDuration") val debuffDuration: JsonElement? = null,

    @SerialName("BonusMoveSpeed") val bonusMoveSpeed: JsonElement? = null,
    @SerialName("BonusSprintSpeed") val bonusSprintSpeed: JsonElement? = null,
    @SerialName("BonusFireRate") val bonusFireRate: JsonElement? = null,
    @SerialName("BonusHealthRegen") val bonusHealthRegen: JsonElement? = null,
    @SerialName("OutOfCombatHealthRegen") val outOfCombatHealthRegen: JsonElement? = null,
    @SerialName("BonusClipSizePercent") val bonusClipSizePercent: JsonElement? = null,
    @SerialName("BonusClipSize") val bonusClipSize: JsonElement? = null,
    @SerialName("BonusBulletSpeedPercent") val bonusBulletSpeedPercent: JsonElement? = null,
    @SerialName("BonusAbilityDurationPercent") val bonusAbilityDurationPercent: JsonElement? = null,
    @SerialName("BonusAbilityCharges") val bonusAbilityCharges: JsonElement? = null,
    @SerialName("BonusMeleeDamagePercent") val bonusMeleeDamagePercent: JsonElement? = null,

    @SerialName("BulletResist") val bulletResist: JsonElement? = null,
    @SerialName("TechResist") val techResist: JsonElement? = null,
    @SerialName("TechPower") val techPower: JsonElement? = null,
    @SerialName("TechPowerPercent") val techPowerPercent: JsonElement? = null,
    @SerialName("TechRangeMultiplier") val techRangeMultiplier: JsonElement? = null,
    @SerialName("TechRadiusMultiplier") val techRadiusMultiplier: JsonElement? = null,

    @SerialName("BulletLifestealPercent") val bulletLifestealPercent: JsonElement? = null,
    @SerialName("AbilityLifestealPercentHero") val abilityLifestealPercentHero: JsonElement? = null,

    @SerialName("BaseAttackDamagePercent") val baseAttackDamagePercent: JsonElement? = null,
    @SerialName("CooldownReduction") val cooldownReduction: JsonElement? = null,
    @SerialName("StatusResistancePercent") val statusResistancePercent: JsonElement? = null,
    @SerialName("Stamina") val stamina: JsonElement? = null,
    @SerialName("StaminaCooldownReduction") val staminaCooldownReduction: JsonElement? = null,
    @SerialName("ProcChance") val procChance: JsonElement? = null,
    @SerialName("MaxStacks") val maxStacks: JsonElement? = null,
    @SerialName("BulletArmorReduction") val bulletArmorReduction: JsonElement? = null,
    @SerialName("MagicResistReduction") val magicResistReduction: JsonElement? = null,
    @SerialName("HealAmpReceivePenaltyPercent") val healAmpReceivePenaltyPercent: JsonElement? = null,
    @SerialName("HealAmpRegenPenaltyPercent") val healAmpRegenPenaltyPercent: JsonElement? = null,
    @SerialName("FireRateSlow") val fireRateSlow: JsonElement? = null,
)